---
output: html_document
---

###Sampling Design
#author: Derek Corcoran

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

First we load the spatial packages

```{r}
library("raster", lib.loc="~/R/win-library/3.2")
library("rasterVis", lib.loc="~/R/win-library/3.2")
library("maps", lib.loc="~/R/win-library/3.2")
library("maptools", lib.loc="~/R/win-library/3.2")
library("rgdal", lib.loc="~/R/win-library/3.2")
```
read rasters

```{r}
bc <- readGDAL("C:/Users/usuario/Bats_California/layers/burn_canopy.asc")
bc<-raster (bc)
plot(bc, breaks= c(0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5,256))
bb <- readGDAL("C:/Users/usuario/Bats_California/layers/burn_basal.asc")
bb<-raster (bb)
plot(bb)
bs <- readGDAL("C:/Users/usuario/Bats_California/layers/burn_severity.asc")
bs<-raster (bs)
plot(bs)
topo <- readGDAL("C:/Users/usuario/Bats_California/layers/plumastopo.asc")
topo<-raster (topo)
plot(topo)
summary(bs)
```

#Check for correlation between rasters

```{r}
burn <-brick(bc, bs, bb)
plot (burn)
layerStats(burn, "pearson",na.rm=TRUE)
```
